[package]
name = "mnist"
version = "0.1.0"
authors = ["xiaanyin <xiaanyin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.2.0"
